"""Warp movie (frame-series) motion model.

Port of ``Movie.GetPositionInAllFrames`` (warp/WarpLib/Movie/Movie.cs:1387),
which warpylib does not implement. Golden-tested against the real C# chain
(tests/golden/movie_positions.json, generated by the M0b harness with nonzero
movement + local grids, two pyramid levels and FractionFrames != 1).

Map direction (frozen contract, docs/conventions.md): for a point ``x`` in
the corrected/reference frame, returns its source sample position in raw
frame ``f`` — Warp subtracts every grid from the input coordinate::

    grid_coords            = (x/Ix, y/Iy, f/(F-1))
    grid_coords_fractional = (x/Ix, y/Iy, f/(F-1) * FractionFrames)
    raw = x - GridMovement(frac) - GridLocal(frac) - sum_p Pyramid_p(NON-frac)

All shift grids are in Angstrom. The XML does NOT carry NFrames, the physical
image dimensions, or FractionFrames — they are runtime state and must be
supplied by the caller (from the raw movie or explicit arguments).
"""

from __future__ import annotations

from pathlib import Path

import torch
from warpylib.movie import Movie
from warpylib.movie.io import load_meta


class WarpMovieModel:
    def __init__(
        self,
        movie: Movie,
        *,
        n_frames: int,
        image_dims_a: tuple[float, float],
        fraction_frames: float = 1.0,
    ):
        if n_frames < 1:
            raise ValueError("n_frames must be >= 1")
        if min(image_dims_a) <= 0:
            raise ValueError(f"bad image_dims_a {image_dims_a}")
        self.movie = movie
        self.n_frames = int(n_frames)
        self.image_dims_a = torch.tensor(image_dims_a, dtype=torch.float64)
        self.fraction_frames = float(fraction_frames)

    @classmethod
    def from_xml(
        cls,
        xml_path: str | Path,
        *,
        n_frames: int,
        image_dims_a: tuple[float, float],
        fraction_frames: float = 1.0,
    ) -> WarpMovieModel:
        movie = Movie()
        load_meta(movie, str(xml_path))
        return cls(
            movie,
            n_frames=n_frames,
            image_dims_a=image_dims_a,
            fraction_frames=fraction_frames,
        )

    @property
    def n_projections(self) -> int:
        return self.n_frames

    def _shift_sum(self, points_2d: torch.Tensor, with_local: bool) -> torch.Tensor:
        """Total subtracted shift (F, N, 2) at the input coordinates."""
        n = points_2d.shape[0]
        f_count = self.n_frames
        grid_step = 1.0 / max(1, f_count - 1)

        x_norm = (points_2d[:, 0].to(torch.float32) / float(self.image_dims_a[0]))
        y_norm = (points_2d[:, 1].to(torch.float32) / float(self.image_dims_a[1]))

        shifts = torch.zeros(f_count, n, 2, dtype=torch.float32)
        for f in range(f_count):
            z = f * grid_step
            coords = torch.stack(
                [x_norm, y_norm, torch.full_like(x_norm, z)], dim=-1
            )
            coords_frac = coords.clone()
            coords_frac[:, 2] = z * self.fraction_frames

            sx = self.movie.grid_movement_x.get_interpolated(coords_frac)
            sy = self.movie.grid_movement_y.get_interpolated(coords_frac)
            if with_local:
                sx = sx + self.movie.grid_local_x.get_interpolated(coords_frac)
                sy = sy + self.movie.grid_local_y.get_interpolated(coords_frac)
                for px, py in zip(self.movie.pyramid_shift_x, self.movie.pyramid_shift_y):
                    sx = sx + px.get_interpolated(coords)  # pyramids: NON-fractional z
                    sy = sy + py.get_interpolated(coords)
            shifts[f, :, 0] = sx
            shifts[f, :, 1] = sy
        return shifts

    def _map(self, points_2d: torch.Tensor, with_local: bool) -> tuple[torch.Tensor, torch.Tensor]:
        if points_2d.shape[-1] != 2:
            raise ValueError(f"points_2d must be (N, 2), got {tuple(points_2d.shape)}")
        raw = points_2d.to(torch.float32)[None, :, :] - self._shift_sum(points_2d, with_local)
        dims = self.image_dims_a.to(raw)
        valid = (
            (raw[..., 0] >= 0)
            & (raw[..., 0] <= dims[0])
            & (raw[..., 1] >= 0)
            & (raw[..., 1] <= dims[1])
            & torch.isfinite(raw).all(dim=-1)
        )
        return raw, valid

    def map_image(self, points_2d: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Full model: (N, 2) A -> raw positions (F, N, 2) A + valid (F, N)."""
        return self._map(points_2d, with_local=True)

    def map_image_global(self, points_2d: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Global drift only (the (1,1,F) GridMovement)."""
        return self._map(points_2d, with_local=False)
